### ISSUE TITLE
Error: module :rbnf_lexer is not available

### ISSUE THREAD

**Issue by GleisonOliveira** [elixir-cldr/cldr_numbers#33]
Hello everyone.

I'm configuring the lib in a project, but when I try to compile, I receive the following error

```
** (UndefinedFunctionError) function :rbnf_lexer.string/1 is undefined (module :rbnf_lexer is not available)
    :rbnf_lexer.string([8722, 8594, 8594])
    (ex_cldr_numbers 2.28.0) lib/cldr/number/rbnf/rule.ex:32: Cldr.Rbnf.Rule.parse/1
    (ex_cldr_numbers 2.28.0) lib/cldr/number/rbnf/processor.ex:159: anonymous fn/6 in Cldr.Rbnf.Processor.define_rules/3
    (ex_cldr_numbers 2.28.0) lib/cldr/number/rbnf/processor.ex:177: anonymous fn/6 in Cldr.Rbnf.Processor.iterate_rules/3
    (elixir 1.13.4) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ex_cldr_numbers 2.28.0) lib/cldr/number/rbnf/processor.ex:176: anonymous fn/4 in Cldr.Rbnf.Processor.iterate_rules/3
    (stdlib 3.17.2.1) maps.erl:410: :maps.fold_1/3
    (ex_cldr_numbers 2.28.0) lib/cldr/number/rbnf/processor.ex:175: anonymous fn/4 in Cldr.Rbnf.Processor.iterate_rules/3
```

I'm using
Elixir: 1.13.4 (running inside a docker container)
Project: Using umbrella

My current deps are:
```
{:cache, in_umbrella: true},
      {:queue, in_umbrella: true},
      {:response, in_umbrella: true},
      {:phoenix_pubsub, "~> 2.0"},
      {:phoenix_html, "~> 3.0"},
      {:phoenix_swoosh, "~> 1.0"},
      {:ecto_sql, "~> 3.6"},
      {:postgrex, ">= 0.0.0"},
      {:jason, "~> 1.2"},
      {:swoosh, "~> 1.3"},
      {:guardian, "~> 2.0"},
      {:guardian_db, "~> 2.0"},
      {:comeonin, "~> 4.0"},
      {:bcrypt_elixir, "~> 1.0"},
      {:tarams, "~> 1.6.0"},
      {:timex, "~> 3.0"},
      {:scrivener_ecto, "~> 2.0"},
      {:hackney, "~> 1.18"},
      {:libphonenumber, "~> 0.1.0"},
      {:cpf, "~> 1.0"},
      {:tesla, "~> 1.4"},
      {:hackney, "~> 1.17"},
      {:quantum, "~> 3.0"},
      {:cc_validation, "~> 0.1.1"},
      {:ex_cldr, "~> 2.34.0"},
      {:ex_cldr_numbers, "~> 2.28"}
```

My Cldr configuration is:

```
defmodule Host.Cldr do
    use Cldr,
        default_locale: "pt",
        locales: ["pt"],
        add_fallback_locales: false,
        data_dir: "./priv/cldr",
        providers: [Cldr.Number],
        generate_docs: true
end
```

How can I solve this problem?

**Comment by kipcole9** [comment]
The `:rbnf_lexer` module is an erlang module (actually a [leex](https://www.erlang.org/doc/man/leex.html) generated module).  It should be automatically compiled by Elixir.  It seems it is not being compiled for some reason.  

I suggest you:

1. run `mix compile --list` to ensure the `leex`, and `erlang` compilers are configured:2. 
```elixir
% mix compile --list
mix compile.app       # Writes an .app file
mix compile.elixir    # Compiles Elixir source files
mix compile.erlang    # Compiles Erlang source files
mix compile.leex      # Compiles Leex source files
mix compile.protocols # Consolidates all protocols in all paths
mix compile.yecc      # Compiles Yecc source files

Enabled compilers: yecc, leex, erlang, elixir, app, protocols
```
2. run `mix compile --deps ex_cldr_numbers --force` to make sure its correctly compiled. You should see at least:
```elixir
Compiling 2 files (.yrl)
Compiling 2 files (.xrl)  <- this compiles the rbnf_lexer.xrl lexer into erlang
Compiling 4 files (.erl) <- this compiles rbnf_lexer.erl
Compiling 28 files (.ex)
....
```
3. take a look to see that `_build/dev/lib/ex_cldr_numbers/ebin/rbnf_lexer.beam` exists

Let me know what you find?

**Comment by GleisonOliveira** [comment]
Running the command `mix compile --list` i have:
```
mix compile.app         # Writes an .app file
mix compile.elixir      # Compiles Elixir source files
mix compile.elixir_make # Runs `make` in the current project
mix compile.erlang      # Compiles Erlang source files
mix compile.leex        # Compiles Leex source files
mix compile.phoenix     # Compiles Phoenix source files that support code reloading
mix compile.protocols   # Consolidates all protocols in all paths
mix compile.yecc        # Compiles Yecc source files

Enabled compilers: yecc, leex, erlang, elixir, app, protocols
```

The file `_build/dev/lib/ex_cldr_numbers/ebin/rbnf_lexer.beam` exists after compilation, but when compiles, just the messsages are showed
```
Compiling 4 files (.erl)
Compiling 26 files (.ex)
Generated ex_cldr_numbers app
```

**Comment by kipcole9** [comment]
A `mix deps.compile ex_cldr_numbers --force` (note the `--force` should also force recompile the `rbnf_lexer.xrl` file. But I am also confused that if `rbnf_lexer.beam` exists why it isn't being loaded!

One more thing to check, since you're on Linux (I'm assuming since you're running in Docker) is that Erlang's parse tools are installed?
```bash
apt-get --list erlang-parsetools
```

Last thought for now is to check that `rbnf_lexer` is capable of being loaded:
```elixir
iex> Code.ensure_loaded? :rbnf_lexer
true
```

**Comment by GleisonOliveira** [comment]
The command `mix deps.compile ex_cldr_numbers --force` solves the problem, thanks for the help 😄
